base_url = "https://puzzleshark.github.io/banning-band/"
title = "Banning Band"
description = "Official website of Banning Band"
default_language = "en"

# Zola configuration
build_search_index = false
generate_feeds = false

[extra]
author = "Banning Band"