base_url = "https://groove.banning.ca/"
title = "Banning Groove"
description = "Official website of Banning Groove"
default_language = "en"

# Zola configuration
build_search_index = false
generate_feeds = false

[extra]
author = "Banning Band"