base_url = "https://velvet.banning.ca/"
title = "Banning Velvet"
description = "Official website of Banning Velvet"
default_language = "en"

# Zola configuration
build_search_index = false
generate_feeds = false

[extra]
author = "Banning Band"